"use client";

import { ReactNode, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { fetchSummary, SummaryData } from "@/app/lib/api";

type PipelineStage = {
  num: string;
  label: string;
  detail: string;
  from: string;
  through: string;
  outcome: string;
};

const PIPELINE_STAGES = [
  {
    num: "01",
    label: "Ingest",
    detail: "Snapshot and normalize",
    from: "Starts with a raw export of survey answers, free-text comments, and dataset metadata.",
    through: "Checks schema, fixes encoding issues, aligns locale fields, and freezes a versioned snapshot for the run.",
    outcome: "Ends with a clean, analysis-ready batch where every response is normalized and traceable.",
  },
  {
    num: "02",
    label: "Psychometrics",
    detail: "CFA and reliability checks",
    from: "Starts with normalized survey item responses and latent factor definitions.",
    through: "Runs reliability checks, factor fit diagnostics, and flags unstable or low-quality item groupings.",
    outcome: "Ends with validated measurement signals that can safely feed downstream modeling.",
  },
  {
    num: "03",
    label: "Splits",
    detail: "Leak-safe train and test split",
    from: "Starts with validated records and the set of target labels chosen for the experiment.",
    through: "Creates stratified train and test partitions while preventing leakage across linked records and cohorts.",
    outcome: "Ends with reproducible split manifests ready for model training and evaluation.",
  },
  {
    num: "04",
    label: "Text Tasks",
    detail: "Language, sentiment, detail",
    from: "Starts with comments, language metadata, and the train and test partitions.",
    through: "Runs text preprocessing plus task-specific inference for language, sentiment, and response detail signals.",
    outcome: "Ends with structured text features and predictions aligned back to each response.",
  },
  {
    num: "05",
    label: "Fusion",
    detail: "Text + survey signal blend",
    from: "Starts with survey-derived factors and model-generated text features.",
    through: "Combines both signal families into unified feature tables and calibrates their joint contribution.",
    outcome: "Ends with a fused representation that captures both stated ratings and narrative feedback.",
  },
  {
    num: "06",
    label: "Contradiction",
    detail: "Flag rating and text mismatch",
    from: "Starts with fused records containing both scalar ratings and text interpretations.",
    through: "Searches for disagreement patterns, inconsistent sentiment, and high-risk responses needing review.",
    outcome: "Ends with contradiction flags and severity markers for quality control and reporting.",
  },
  {
    num: "07",
    label: "Evaluate",
    detail: "Macro F1 and fit diagnostics",
    from: "Starts with model outputs, true labels, and pipeline diagnostics from earlier stages.",
    through: "Calculates evaluation metrics, compares fit quality, and surfaces regressions across tasks and cohorts.",
    outcome: "Ends with a final performance snapshot that can be compared across runs.",
  },
  {
    num: "08",
    label: "Report",
    detail: "Model cards and run artifacts",
    from: "Starts with the full set of metrics, artifacts, flags, and run metadata generated by the pipeline.",
    through: "Packages outputs into model cards, summaries, downloadable artifacts, and audit-friendly metadata.",
    outcome: "Ends with a complete report bundle ready for review, export, and long-term traceability.",
  },
] satisfies PipelineStage[];

const SectionLabel = ({ children }: { children: ReactNode }) => (
  <div className="db-section-label">{children}</div>
);

export default function DashboardPage() {
  const [summary, setSummary] = useState<SummaryData | null>(null);
  const [summaryStatus, setSummaryStatus] = useState<"loading" | "ready" | "error">(
    "loading"
  );
  const [activeStageIndex, setActiveStageIndex] = useState(0);
  const [stageDirection, setStageDirection] = useState<"forward" | "backward">("forward");
  const [isStageExpanded, setIsStageExpanded] = useState(false);

  useEffect(() => {
    fetchSummary()
      .then((data) => {
        setSummary(data);
        setSummaryStatus("ready");
      })
      .catch(() => {
        setSummary(null);
        setSummaryStatus("error");
      });
  }, []);

  const stats = useMemo(
    () => [
      {
        value: summary ? summary.total_datasets.toLocaleString() : "-",
        label: "Datasets",
      },
      {
        value: summary ? summary.total_models.toLocaleString() : "-",
        label: "Registered Models",
      },
      {
        value: summary ? summary.total_analyses.toLocaleString() : "-",
        label: "Analyses",
      },
      {
        value: summary ? summary.total_responses.toLocaleString() : "-",
        label: "Responses",
      },
      {
        value: summary ? summary.n_latent_factors.toLocaleString() : "-",
        label: "Latent Factors",
      },
      {
        value: summary ? summary.n_survey_items.toLocaleString() : "-",
        label: "Survey Items",
      },
    ],
    [summary]
  );

  const summaryStatusLabel =
    summaryStatus === "loading"
      ? "syncing summary..."
      : summaryStatus === "ready"
        ? "summary synced"
        : "summary unavailable";

  const headlineCount = summary
    ? (
        summary.total_datasets +
        summary.total_models +
        summary.total_analyses
      ).toLocaleString()
    : "-";

  const activeStage = PIPELINE_STAGES[activeStageIndex];
  const isFirstStage = activeStageIndex === 0;
  const isLastStage = activeStageIndex === PIPELINE_STAGES.length - 1;
  const upcomingStage = isLastStage ? null : PIPELINE_STAGES[activeStageIndex + 1];
  const stageProgressWidth = `${((activeStageIndex + 1) / PIPELINE_STAGES.length) * 100}%`;
  const activeStageDetailsId = `pipeline-stage-${activeStage.num}-details`;

  function handleStageChange(nextIndex: number) {
    if (nextIndex < 0 || nextIndex >= PIPELINE_STAGES.length || nextIndex === activeStageIndex) {
      return;
    }

    setStageDirection(nextIndex > activeStageIndex ? "forward" : "backward");
    setActiveStageIndex(nextIndex);
  }

  return (
    <div className="db-shell page-standard animate-fade-up">
      <section className="db-hero">
        <div className="dot-grid db-hero-grid" aria-hidden="true" />
        <div className="db-hero-content">
          <div>
            <div className="db-kicker">
              <span className="db-kicker-dot" />
              Multilingual Batch Analysis
            </div>
            <h1 className="db-title">
              Student Feedback
              <br />
              <span>Command Dashboard</span>
            </h1>
            <p className="db-subtitle">
              One workspace for psychometrics, supervised text models, and reproducible
              experiment tracking across RU and KZ student feedback.
            </p>
            <div className="db-chip-row">
              <span className="db-chip">8-stage pipeline</span>
              <span className="db-chip">batch-only execution</span>
              <span className="db-chip">traceable artifacts</span>
            </div>
            <div className="db-cta-row">
              <Link href="/runs/new" className="db-cta-primary">
                Run Pipeline
              </Link>
              <Link href="/runs" className="db-cta-secondary">
                View Run History
              </Link>
            </div>
          </div>

          <div className="db-stat-grid">
            <div className="db-stat-card db-stat-card-highlight">
              <div className="db-stat-label">Active Inventory</div>
              <div className="db-stat-value">{headlineCount}</div>
              <div className="db-stat-note">datasets + models + analyses</div>
            </div>
            {stats.map(({ value, label }) => (
              <div key={label} className="db-stat-card">
                <div className="db-stat-value">{value}</div>
                <div className="db-stat-label">{label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="db-panel">
        <div className="db-panel-header">
          <SectionLabel>Pipeline Stages</SectionLabel>
          <span className="db-inline-status">{summaryStatusLabel}</span>
        </div>
        <div className="db-stage-carousel" aria-label="Pipeline stages">
          <button
            type="button"
            className="db-stage-nav db-stage-nav--prev"
            onClick={() => handleStageChange(activeStageIndex - 1)}
            disabled={isFirstStage}
            aria-label="Go to previous stage"
          >
            <span aria-hidden="true" className="db-stage-nav-icon">
              &lt;
            </span>
          </button>

          <div className="db-stage-viewport" aria-live="polite" aria-atomic="true">
            <div
              key={activeStage.num}
              className={`db-stage-spotlight db-stage-spotlight--${stageDirection}`}
            >
              <div className="db-stage-spotlight-meta">
                <span className="db-stage-spotlight-overline">Stage {activeStage.num}</span>
                <span className="db-stage-spotlight-counter">
                  {activeStageIndex + 1} / {PIPELINE_STAGES.length}
                </span>
              </div>

              <div className="db-stage-spotlight-grid">
                <div className="db-stage-spotlight-main">
                  <span className="db-stage-spotlight-num">{activeStage.num}</span>
                  <h2 className="db-stage-spotlight-title">{activeStage.label}</h2>
                  <p className="db-stage-spotlight-detail">{activeStage.detail}</p>
                </div>

                <div className="db-stage-spotlight-rail">
                  <div className="db-stage-progress-label">Pipeline progress</div>
                  <div className="db-stage-progress-track" aria-hidden="true">
                    <span
                      className="db-stage-progress-fill"
                      style={{ width: stageProgressWidth }}
                    />
                  </div>
                  <div className="db-stage-progress-copy">
                    {isLastStage
                      ? "Final stage reached"
                      : `${PIPELINE_STAGES.length - activeStageIndex - 1} stages remaining`}
                  </div>
                  <div className="db-stage-next-label">
                    {upcomingStage ? "Up next" : "Status"}
                  </div>
                  <div className="db-stage-next-value">
                    {upcomingStage ? upcomingStage.label : "Pipeline complete"}
                  </div>
                  <button
                    type="button"
                    className={`db-stage-expand-toggle${isStageExpanded ? " is-open" : ""}`}
                    aria-expanded={isStageExpanded}
                    aria-controls={activeStageDetailsId}
                    onClick={() => setIsStageExpanded((current) => !current)}
                  >
                    <span>{isStageExpanded ? "Hide full stage breakdown" : "Show full stage breakdown"}</span>
                    <span aria-hidden="true" className="db-stage-expand-toggle-icon">
                      v
                    </span>
                  </button>
                </div>
              </div>

              <div
                id={activeStageDetailsId}
                className={`db-stage-detail-drawer${isStageExpanded ? " is-open" : ""}`}
              >
                <div className="db-stage-detail-drawer-inner">
                  <div className="db-stage-detail-grid">
                    <div className="db-stage-detail-item">
                      <div className="db-stage-detail-label">From</div>
                      <p className="db-stage-detail-copy">{activeStage.from}</p>
                    </div>
                    <div className="db-stage-detail-item">
                      <div className="db-stage-detail-label">Process</div>
                      <p className="db-stage-detail-copy">{activeStage.through}</p>
                    </div>
                    <div className="db-stage-detail-item">
                      <div className="db-stage-detail-label">Outcome</div>
                      <p className="db-stage-detail-copy">{activeStage.outcome}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <button
            type="button"
            className="db-stage-nav db-stage-nav--next"
            onClick={() => handleStageChange(activeStageIndex + 1)}
            disabled={isLastStage}
            aria-label="Go to next stage"
          >
            <span aria-hidden="true" className="db-stage-nav-icon">
              &gt;
            </span>
          </button>
        </div>

        <div className="db-stage-pagination" aria-label="All pipeline stages">
          {PIPELINE_STAGES.map((stage, index) => (
            <button
              key={stage.num}
              type="button"
              className={`db-stage-pill${index === activeStageIndex ? " is-active" : ""}`}
              onClick={() => handleStageChange(index)}
              aria-pressed={index === activeStageIndex}
              aria-label={`Open stage ${stage.num}: ${stage.label}`}
            >
              <span className="db-stage-pill-num">{stage.num}</span>
              <span className="db-stage-pill-label">{stage.label}</span>
            </button>
          ))}
        </div>
      </section>
    </div>
  );
}
